Repository MNisarAli/recipe_app, pull requests merged in 2023-10, with the labels that each got.

#12 Registration and Login Page
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/users_controller.rb
  app/helpers/users_helper.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/application.html.erb
  app/views/users/index.html.erb
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20231010095026_devise_create_users.rb
  db/migrate/20231010095649_add_name_role_to_users.rb
  db/schema.rb
  spec/helpers/users_helper_spec.rb
  spec/models/user_spec.rb
  spec/requests/users_spec.rb
Labels: authentication

#13 Recipe App - Public Recipe List Implementation
  app/assets/stylesheets/public_recipes.css
  app/controllers/public_recipes_controller.rb
  app/helpers/public_recipes_helper.rb
  app/models/recipe.rb
  app/views/public_recipes/index.html.erb
  config/routes.rb
  db/migrate/20231010161912_create_recipes.rb
  db/schema.rb
  spec/helpers/public_recipes_helper_spec.rb
  spec/models/recipe_spec.rb
  spec/requests/public_recipes_spec.rb
Labels: enhancement

#15 Recipe App - Recipe Details and New Form Implementation
  app/controllers/recipes_controller.rb
  app/views/recipes/index.html.erb
  app/views/recipes/new.html.erb
  app/views/recipes/show.html.erb
Labels: enhancement, authorization

#16 Add Food list page and add new food page
  app/controllers/foods_controller.rb
  app/helpers/foods_helper.rb
  app/models/ability.rb
  app/models/food.rb
  app/models/user.rb
  app/views/foods/index.html.erb
  app/views/foods/new.html.erb
  app/views/users/index.html.erb
  config/routes.rb
  db/migrate/20231012034612_create_foods.rb
  db/migrate/20231012034700_add_users_ref_to_foods.rb
  db/schema.rb
  spec/helpers/foods_helper_spec.rb
  spec/models/food_spec.rb
  spec/requests/foods_spec.rb
Labels: enhancement, authorization

#17 Recipe App - General Shopping List Implementation
  app/controllers/public_recipes_controller.rb
  app/controllers/recipe_foods_controller.rb
  app/controllers/shopping_lists_controller.rb
  app/helpers/recipe_foods_helper.rb
  app/helpers/shopping_lists_helper.rb
  app/models/food.rb
  app/models/recipe.rb
  app/models/recipe_food.rb
  app/views/public_recipes/index.html.erb
  app/views/recipe_foods/new.html.erb
  app/views/recipes/show.html.erb
  app/views/shopping_lists/index.html.erb
  config/routes.rb
  db/migrate/20231011053225_create_recipes.rb
  db/migrate/20231011055251_add_users_ref_to_recipes.rb
  db/migrate/20231012103923_create_recipe_foods.rb
  db/schema.rb
  spec/helpers/recipe_foods_helper_spec.rb
  spec/helpers/shopping_lists_helper_spec.rb
  spec/models/recipe_food_spec.rb
  spec/requests/recipe_foods_spec.rb
  spec/requests/shopping_lists_spec.rb
Labels: enhancement, authorization

#19 Recipe App - N+1 Query Optimization implementation
  app/controllers/shopping_lists_controller.rb
Labels: enhancement, performance

#22 Testing
  .rspec
  app/controllers/foods_controller.rb
  app/controllers/users_controller.rb
  app/models/food.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/foods/index.html.erb
  app/views/foods/new.html.erb
  app/views/layouts/_navigation.html.erb
  app/views/users/index.html.erb
  config/environments/test.rb
  db/schema.rb
  spec/integrations/food_index_spec.rb
  spec/integrations/food_new_spec.rb
  spec/integrations/public_recipes_index_spec.rb
  spec/integrations/recipe_foods_new_spec.rb
  spec/integrations/recipe_index_spec.rb
  spec/integrations/recipes_new_spec.rb
  spec/integrations/recipes_show_spec.rb
  spec/integrations/shopping_lists_index_spec.rb
  spec/models/food_spec.rb
  spec/models/recipe_food_spec.rb
  spec/models/recipe_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/requests/foods_spec.rb
  spec/requests/public_recipes_spec.rb
  spec/requests/recipe_foods_spec.rb
  spec/requests/recipes_spec.rb
  spec/requests/shopping_lists_spec.rb
  spec/requests/users_spec.rb
  spec/spec_helper.rb
Labels: unit-test, integration-test

#21 Styling
  app/assets/images/food.jpg
  app/assets/stylesheets/application.css
  app/assets/stylesheets/foods.css
  app/assets/stylesheets/public_recipes.css
  app/assets/stylesheets/recipe_foods.css
  app/assets/stylesheets/recipes.css
  app/assets/stylesheets/shopping_list.css
  app/assets/stylesheets/users.css
  app/views/foods/index.html.erb
  app/views/foods/new.html.erb
  app/views/public_recipes/index.html.erb
  app/views/recipe_foods/new.html.erb
  app/views/recipes/index.html.erb
  app/views/recipes/new.html.erb
  app/views/recipes/show.html.erb
  app/views/shopping_lists/index.html.erb
  app/views/users/index.html.erb
Labels: enhancement, ui/ux

#24 Update project readme file
  README.md
Labels: documentation, enhancement
